# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-21 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='API')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='应用名称')),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Application', verbose_name='所属应用'),
        ),
    ]
